stages:
  clean:
    cmd: python src/clean_data.py
    deps:
      - data/raw/data.csv
    outs:
      - data/processed/cleaned.csv
    params:
      - clean_params

  featurize:
    cmd: python src/featurize.py
    deps:
      - data/processed/cleaned.csv
    outs:
      - data/processed/features.csv
    params:
      - feature_params

  train:
    cmd: python src/train_model.py
    deps:
      - data/processed/features.csv
    outs:
      - models/model.pkl
    params:
      - train_params

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
    outs:
      - metrics/scores.json